"""APIs for filter annotation modules"""

# Sample API from viewer/AI studio to fetch all WSIs of a definite type, e.g. Tumor positive
#
# Label types: class       -> tile classification
#              bbox        -> bounding box (4 points)
#              segmentation-> 16 boundary points in the border of a region segmented by a model
#              annotation  -> manual annotation points
#              regression  -> any statistic generated by regression 
# Institution: Empty list if data to be fetched from all institutions
#              A list of strings, for specific institutions.
SAMLE_JSON_QUERY_IMAGE_TYPE = {
    "label_type":["class","segmentation"]
    "image_type":["Tumor","PCD"],
    "institution":[]
}

# Sample API from viewer/AI studio to fetch all labels within a viewport from a specific image
#
# viewport-> [xmin,ymin,xmax,ymax]
# inst_id -> numeric instance id, if a specific annotation instance to be fetched. Otherwise empty list.
SAMLE_JSON_QUERY_VIEWPORT = {
    "image_name":["2001V401001_55"]
    "magnification":40
    "viewport":[100,200,500,600]
    "inst_id":[]
}

# Sample API from viewer/AI studio to fetch first 4 instances of definite type of labels within a viewport from a specific image
SAMLE_JSON_QUERY_VIEWPORT_LABEL = {
    "image_name":["2001V401001_55"],
    "label_type":["annotation"],
    "image_type":[],
    "magnification":40
    "viewport":[100,200,500,600]
    "instance_id":[0,1,2,3]
}

# Sample API from viewer/AI studio to fetch all labels of a definite image type, from e.g. Tumor positive
SAMLE_JSON_QUERY_VIEWPORT_IMAGE_TYPE = {
    "image_name":["2001V401001_55"],
    "label_type":["annotation","segmentation"],
    "image_type":["Tumor","PCD"],
    "magnification":40
    "viewport":[100,200,500,600]
    "instance_id":[]
}

# Sample API from viewer/AI studio to update annotation points for a single image 
#
# label type and image types are not in this APIs as only mannual annotations can be updated
# through viewer/AI studio user interface
#
# insert /update points: [(x,y,label)]
SAMLE_JSON_UPDATE = {
    "image_name":"2001V401001_55",
    "magnification":40
    "insert":{
        [(850,210,0),(890,200,0)]
    }
    "delete":{
        [(8700,2100,3),(90,20,1)]
    }
    "creator":"Dr. Jaya"
    "institution":"Pramana"
}

# Sample JSON for loading annotation data from Unified model to database
#
# Points : [x-coordinate,y-coordinate,label,instance_id(unique number 
# identifying all points for same annotation instance)]
SAMPLE_JSON_UNIFIED = {
    "image_name":"H-1535-21-A2_H01IBB82R-61",
    "label_type":"segmentation",
    "Image_type":"",
    "points":[
        [100,200,"nuclei",0],
        [102,250,"nuclei",0],
        [200,200,"nuclei",0],
        [400,200,"nuclei",1],
        [402,250,"nuclei",1],
        [500,200,"nuclei",1]
    ]
    "magnification":40
    "creator":"Daniel. S. Samuel"
    "institution":"Mayo Clinic"

}